jobs:
  install-node:
    docker:
      - image: 'node:12.2.0-alpine'
    steps:
      - checkout
      - run: yarn install
version: 2.1
workflows:
  create_environment:
    jobs:
      - install-node
