jobs:
  build:
    working_directory: ~/app
    docker:
      - image: 'node:alpine'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:prod .
version: 2.1
workflows:
  build-master:
    jobs:
      - build:
        filters:
          branches:
            only: master
